### ISSUE TITLE
Fixes to "add collections" section of form

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_webclient#12]
![Screenshot 2024-04-23 at 9 41 11 AM](https://github.com/azgs/azlibrary_webclient/assets/10422595/00807057-3ef7-47b3-b02f-96f2a46ce58a)

1. The REMOVE button does not do anything. 
2. Also, may be nice to have a corresponding CLEAR button in case if I hit LOAD on the wrong collection by accident.

**Comment by NoisyFlowers** [comment]
Remove is fixed in 06a9dcf35e2113d96b2669a6fa1f596663edc33d

**Comment by NoisyFlowers** [comment]
Skipping 2 for now. We'll tackle when we redo the upload client
