### ISSUE TITLE
Unable to load existing collection metadata

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_webclient#13]
![Screenshot 2024-05-13 at 7 21 11 AM](https://github.com/azgs/azlibrary_webclient/assets/10422595/034f0b5a-60f3-4fcb-a9c9-a27b3b32648f)

It does not matter what collection you pick. None work.

**Comment by NoisyFlowers** [comment]
It appears to work for some collections.

![image](https://github.com/azgs/azlibrary_webclient/assets/12547812/d495cb15-0dcd-40eb-a871-2c5067711cf2)

Can you provide a collection perm_id for which it does not work?

**Comment by aazaff** [comment]
These did not work for me. I just picked them at random so for me it seems to be 100%. I hope this isn’t one of those things where it works for you but not for me. That’ll make it a b* to troubleshoot…

AGCR-1709677235826-954
ADGM-1707499630122-741
ADGM-1709239328586-905

From: NoisyFlowers ***@***.***>
Date: Monday, May 13, 2024 at 7:50 AM
To: azgs/azlibrary_webclient ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>, Author ***@***.***>
Subject: [EXT]Re: [azgs/azlibrary_webclient] Unable to load existing collection metadata (Issue #13)

External Email

It appears to work for some collections.

image.png (view on web)<https://github.com/azgs/azlibrary_webclient/assets/12547812/d495cb15-0dcd-40eb-a871-2c5067711cf2>

Can you provide a collection perm_id for which it does not work?

**Comment by NoisyFlowers** [comment]
They're all loading for me. 

Maybe your browser has a cached version of the form?

**Comment by aazaff** [comment]
Ugh… yeah that fixed it for me…

From: NoisyFlowers ***@***.***>
Date: Monday, May 13, 2024 at 8:06 AM
To: azgs/azlibrary_webclient ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>, Author ***@***.***>
Subject: [EXT]Re: [azgs/azlibrary_webclient] Unable to load existing collection metadata (Issue #13)

External Email

They're all loading for me.

Maybe your browser has a cached version of the form?
